//! What the screenshot overlay looks like: sizes, colours, durations and
//! the icons' paths (`dev-docs/poltergeist/screenshot.md`, 9.8).
//!
//! **GENERATED. Do not edit this file.** It is written from
//! `src/input/screenshot-look.json` by `python3 tools/gen-screenshot-look.py --write`;
//! change the data and run that. `tools/the-screenshot-look-is-one-set.py`
//! fails when this file is not what the data says. The macOS host has the
//! same data as `ShotLook.swift`, written by the same run.

// Lengths are logical points unless a name says otherwise.

/// A colour and how much of it there is.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Rgba {
    pub r: u8,
    pub g: u8,
    pub b: u8,
    /// 0 to 1.
    pub a: f64,
}

/// One step of a path, in units of the icon's artboard.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Cmd {
    Move(f64, f64),
    Line(f64, f64),
    /// Two control points and the end.
    Cubic(f64, f64, f64, f64, f64, f64),
    Close,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Paint {
    Stroke,
    Fill,
    /// Filled, and stroked in the same colour to round its corners.
    FillAndStroke,
}

/// One shape of an icon. Parts are drawn in order, one over another.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Part {
    pub paint: Paint,
    /// The stroke's width in artboard units; 0 for a fill.
    pub width: f64,
    pub opacity: f64,
    pub cmds: &'static [Cmd],
}

/// Where an icon's ink is when it is drawn into a button cell: the box of
/// the pixels at least half covered, and how many there are.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Ink {
    pub scale: f64,
    /// The cell's side in pixels.
    pub cell: i32,
    pub x: i32,
    pub y: i32,
    pub w: i32,
    pub h: i32,
    pub count: i32,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Icon {
    pub key: &'static str,
    /// The English name, a msgid of `src/input/screenshot.zig`.
    pub name: &'static str,
    pub parts: &'static [Part],
    /// What the generator's own rasteriser made of it; the test of this
    /// crate's rasteriser is that it makes the same.
    pub ink: &'static [Ink],
}

/// The grid the icons are drawn on.
pub mod icon_grid {
    pub const ARTBOARD: f64 = 24.0;
    pub const LIVE_MIN: f64 = 2.0;
    pub const LIVE_MAX: f64 = 22.0;
    pub const STROKE: f64 = 1.75;
    pub const POINTS: f64 = 20.0;
}

pub mod size {
    pub const BUTTON: f64 = 28.0;
    pub const GAP: f64 = 4.0;
    pub const GROUP_GAP: f64 = 12.0;
    pub const PADDING: f64 = 6.0;
    pub const ROW_GAP: f64 = 0.0;
    pub const ROW_DIVIDER: f64 = 0.5;
    pub const PLATE_RADIUS: f64 = 12.0;
    pub const CELL_RADIUS: f64 = 7.0;
    pub const ICON: f64 = 20.0;
    pub const SWATCH: f64 = 16.0;
    pub const SWATCH_EDGE: f64 = 0.5;
    pub const HOVER_EDGE: f64 = 0.5;
    pub const RING: f64 = 1.5;
    pub const GLOW_SIGMA: f64 = 2.0;
    pub const OFFSET: f64 = 8.0;
    pub const PLATE_SHADOW_DY: f64 = 4.0;
    pub const PLATE_SHADOW_SIGMA: f64 = 7.0;
    pub const PLATE_EDGE: f64 = 0.5;
    pub const LABEL_RADIUS: f64 = 8.0;
    pub const TIP_PAD_X: f64 = 10.0;
    pub const TIP_PAD_Y: f64 = 6.0;
    pub const TIP_KEY_GAP: f64 = 8.0;
    pub const TIP_KEY_PAD_X: f64 = 5.0;
    pub const TIP_KEY_PAD_Y: f64 = 2.0;
    pub const TIP_KEY_RADIUS: f64 = 4.0;
    pub const TIP_OFFSET: f64 = 4.0;
    pub const STATUS_PAD_X: f64 = 10.0;
    pub const STATUS_PAD_Y: f64 = 6.0;
    pub const STATUS_DOT: f64 = 8.0;
    pub const STATUS_DOT_HALO: f64 = 3.0;
    pub const STATUS_GAP: f64 = 8.0;
    pub const SIZE_LABEL_PAD_X: f64 = 8.0;
    pub const SIZE_LABEL_PAD_Y: f64 = 5.0;
    pub const SIZE_LABEL_OFFSET: f64 = 6.0;
    pub const SIZE_LABEL_INSET: f64 = 4.0;
    pub const SELECTION_LINE: f64 = 1.0;
    pub const SELECTION_KNOB: f64 = 7.0;
    pub const WINDOW_LINE: f64 = 2.0;
    pub const MOSAIC_FRAME: f64 = 16.0;
    pub const MOSAIC_FRAME_LINE: f64 = 1.0;
    pub const MAGNIFIER_CELLS: f64 = 15.0;
    pub const MAGNIFIER_CELL: f64 = 8.0;
    pub const MAGNIFIER_OFFSET: f64 = 16.0;
    pub const MAGNIFIER_PAD: f64 = 8.0;
    pub const MAGNIFIER_IMAGE_RADIUS: f64 = 6.0;
    pub const MAGNIFIER_GRID_LINE: f64 = 0.5;
    pub const MAGNIFIER_CENTRE_LINE: f64 = 1.5;
    pub const MAGNIFIER_ROW_GAP: f64 = 6.0;
    pub const MAGNIFIER_SWATCH: f64 = 12.0;
}

pub mod glass {
    pub const PLATE_BLUR_SIGMA: f64 = 12.0;
    pub const PLATE_SATURATION: f64 = 1.5;
    pub const PLATE_BRIGHTNESS: f64 = 0.5;
    pub const OUTSIDE_BLUR_SIGMA: f64 = 3.0;
    pub const LUMA_R: f64 = 0.2126;
    pub const LUMA_G: f64 = 0.7152;
    pub const LUMA_B: f64 = 0.0722;
    pub const DOWNSAMPLE_SCALE_AT_LEAST: f64 = 1.75;
    pub const DOWNSAMPLE_HI: f64 = 4.0;
    pub const DOWNSAMPLE_LO: f64 = 2.0;
    pub const BOX_PASSES: f64 = 3.0;
    pub const WAIT_MS: f64 = 50.0;
}

pub mod transition_ms {
    pub const HOVER_IN: f64 = 80.0;
    pub const HOVER_OUT: f64 = 120.0;
    pub const PRESS: f64 = 0.0;
    pub const RELEASE: f64 = 120.0;
    pub const DESELECT: f64 = 100.0;
    pub const WINDOW_SWITCH: f64 = 120.0;
    pub const DRAG_START: f64 = 120.0;
    pub const GRIP_HOVER: f64 = 80.0;
    pub const TIP_DELAY: f64 = 500.0;
    pub const COPIED_FLASH: f64 = 900.0;
}

pub mod text_box {
    pub const LINE: f64 = 1.0;
    pub const DASH: f64 = 4.0;
    pub const OFFSET: f64 = 2.0;
    pub const CARET_WIDTH: f64 = 2.0;
    pub const CARET_HEIGHT_EM: f64 = 1.08;
    pub const CARET_EDGE: f64 = 1.0;
    pub const HALO_NEAR_SIGMA: f64 = 0.5;
    pub const HALO_NEAR_ALPHA: f64 = 0.85;
    pub const HALO_FAR_SIGMA: f64 = 1.25;
    pub const HALO_FAR_ALPHA: f64 = 0.55;
    pub const MARKED_LINE: f64 = 2.0;
    pub const LIGHT_TEXT_LUMINANCE: f64 = 0.5;
    pub const SELECTION_ALPHA: f64 = 0.35;
}

pub mod annotation {
    pub const FRAME_OFFSET: f64 = 4.0;
    pub const FRAME_LINE: f64 = 1.0;
    pub const FRAME_DASH_ON: f64 = 4.0;
    pub const FRAME_DASH_OFF: f64 = 3.0;
    pub const FRAME_RADIUS: f64 = 2.0;
    pub const GRIP: f64 = 7.0;
    pub const GRIP_HOT: f64 = 9.0;
    pub const GRIP_RADIUS: f64 = 1.5;
    pub const GRIP_LINE: f64 = 1.0;
    pub const GRIP_SHADOW: f64 = 0.6;
    pub const GRIP_REACH: f64 = 6.0;
    pub const OUTSIDE_OPACITY: f64 = 0.4;
    pub const TAG_OFFSET: f64 = 12.0;
    pub const DRAG_THRESHOLD: f64 = 3.0;
    pub const DIRTY_RING: f64 = 5.0;
    pub const DIRTY_SHADOW_X: f64 = 14.0;
    pub const DIRTY_SHADOW_TOP: f64 = 10.0;
    pub const DIRTY_SHADOW_BOTTOM: f64 = 18.0;
}

pub mod levels {
    pub const DOTS: [f64; 5] = [3.0, 5.0, 8.0, 11.0, 15.0];
    pub const MOSAIC_CELLS: [f64; 5] = [6.0, 5.0, 4.0, 3.0, 2.0];
}

pub mod colour {
    use super::Rgba;
    pub const PLATE_TINT: Rgba = Rgba { r: 0x1D, g: 0x1F, b: 0x20, a: 0.66 };
    pub const PLATE_OPAQUE: Rgba = Rgba { r: 0x3D, g: 0x3F, b: 0x40, a: 1.0 };
    pub const PLATE_OPAQUE_EDGE: Rgba = Rgba { r: 0x8E, g: 0x8F, b: 0x90, a: 1.0 };
    pub const PLATE_INNER_EDGE: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.22 };
    pub const PLATE_OUTER_EDGE: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.35 };
    pub const PLATE_SHADOW: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.3 };
    pub const ROW_DIVIDER: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.18 };
    pub const INK: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0 };
    pub const INK_DIM: Rgba = Rgba { r: 0xA0, g: 0xA0, b: 0xA0, a: 1.0 };
    pub const INK_OFF: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.32 };
    pub const HOVER: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.14 };
    pub const HOVER_EDGE: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.3 };
    pub const DOWN: Rgba = Rgba { r: 0x41, g: 0x9C, b: 0xFF, a: 0.18 };
    pub const ACCENT: Rgba = Rgba { r: 0x41, g: 0x9C, b: 0xFF, a: 1.0 };
    pub const GLOW: Rgba = Rgba { r: 0x41, g: 0x9C, b: 0xFF, a: 0.4 };
    pub const DONE_DOWN_INK: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0 };
    pub const SWATCH_EDGE: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.3 };
    pub const TIP_KEY_PLATE: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.12 };
    pub const MOSAIC_FRAME: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.45 };
    pub const STATUS_DOT: Rgba = Rgba { r: 0xE0, g: 0x40, b: 0x40, a: 1.0 };
    pub const STATUS_DOT_HALO: Rgba = Rgba { r: 0xE0, g: 0x40, b: 0x40, a: 0.3 };
    pub const OUTSIDE_DIM: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.06 };
    pub const OUTSIDE_DIM_OPAQUE: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.43 };
    pub const KNOB_FILL: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0 };
    pub const BOX_DARK: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.72 };
    pub const BOX_LIGHT: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.95 };
    pub const CARET_EDGE_DARK: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.6 };
    pub const CARET_EDGE_LIGHT: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.75 };
    pub const FRAME_LIGHT: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 0.85 };
    pub const GRIP_FILL: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0 };
    pub const GRIP_SHADOW: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.6 };
    pub const MAGNIFIER_GRID: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.22 };
    pub const MAGNIFIER_CENTRE_OUTER: Rgba = Rgba { r: 0x00, g: 0x00, b: 0x00, a: 0.85 };
    pub const MAGNIFIER_CENTRE_INNER: Rgba = Rgba { r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0 };
    pub const MAGNIFIER_OFF_SCREEN: Rgba = Rgba { r: 0x20, g: 0x20, b: 0x20, a: 1.0 };
}

const SELECT_0: &[Cmd] = &[
    Cmd::Move(6.4, 3.4),
    Cmd::Line(6.4, 18.2),
    Cmd::Line(10.0, 14.9),
    Cmd::Line(12.6, 20.6),
    Cmd::Line(15.0, 19.6),
    Cmd::Line(12.5, 14.0),
    Cmd::Line(17.6, 14.0),
    Cmd::Close,
];
const RECT_0: &[Cmd] = &[
    Cmd::Move(6.5, 5.0),
    Cmd::Line(17.5, 5.0),
    Cmd::Cubic(18.88071, 5.0, 20.0, 6.11929, 20.0, 7.5),
    Cmd::Line(20.0, 16.5),
    Cmd::Cubic(20.0, 17.88071, 18.88071, 19.0, 17.5, 19.0),
    Cmd::Line(6.5, 19.0),
    Cmd::Cubic(5.11929, 19.0, 4.0, 17.88071, 4.0, 16.5),
    Cmd::Line(4.0, 7.5),
    Cmd::Cubic(4.0, 6.11929, 5.11929, 5.0, 6.5, 5.0),
    Cmd::Close,
];
const ELLIPSE_0: &[Cmd] = &[
    Cmd::Move(21.0, 12.0),
    Cmd::Cubic(21.0, 16.28021, 16.97056, 19.75, 12.0, 19.75),
    Cmd::Cubic(7.02944, 19.75, 3.0, 16.28021, 3.0, 12.0),
    Cmd::Cubic(3.0, 7.71979, 7.02944, 4.25, 12.0, 4.25),
    Cmd::Cubic(16.97056, 4.25, 21.0, 7.71979, 21.0, 12.0),
    Cmd::Close,
];
const LINE_0: &[Cmd] = &[
    Cmd::Move(5.0, 19.0),
    Cmd::Line(19.0, 5.0),
];
const ARROW_0: &[Cmd] = &[
    Cmd::Move(5.0, 19.0),
    Cmd::Line(19.0, 5.0),
    Cmd::Move(10.5, 5.0),
    Cmd::Line(19.0, 5.0),
    Cmd::Line(19.0, 13.5),
];
const PEN_0: &[Cmd] = &[
    Cmd::Move(4.0, 20.0),
    Cmd::Line(5.1, 15.3),
    Cmd::Line(16.4, 4.0),
    Cmd::Cubic(17.16063, 3.24361, 18.38937, 3.24361, 19.15, 4.0),
    Cmd::Line(20.0, 4.85),
    Cmd::Cubic(20.75639, 5.61063, 20.75639, 6.83937, 20.0, 7.6),
    Cmd::Line(8.7, 18.9),
    Cmd::Close,
    Cmd::Move(14.4, 6.0),
    Cmd::Line(18.0, 9.6),
];
const HIGHLIGHTER_0: &[Cmd] = &[
    Cmd::Move(9.2, 12.6),
    Cmd::Line(16.0, 4.2),
    Cmd::Cubic(16.52698, 3.56924, 17.46343, 3.48006, 18.1, 4.0),
    Cmd::Line(20.7, 6.1),
    Cmd::Cubic(21.33076, 6.62698, 21.41994, 7.56343, 20.9, 8.2),
    Cmd::Line(14.1, 16.6),
    Cmd::Close,
    Cmd::Move(9.2, 12.6),
    Cmd::Line(8.2, 16.1),
    Cmd::Line(10.6, 18.0),
    Cmd::Line(14.1, 16.6),
    Cmd::Move(8.2, 16.1),
    Cmd::Line(5.6, 19.3),
    Cmd::Line(9.8, 19.3),
    Cmd::Line(10.6, 18.0),
    Cmd::Move(3.5, 21.5),
    Cmd::Line(20.5, 21.5),
];
const TEXT_0: &[Cmd] = &[
    Cmd::Move(5.0, 7.5),
    Cmd::Line(5.0, 5.0),
    Cmd::Line(19.0, 5.0),
    Cmd::Line(19.0, 7.5),
    Cmd::Move(12.0, 5.0),
    Cmd::Line(12.0, 19.0),
    Cmd::Move(9.0, 19.0),
    Cmd::Line(15.0, 19.0),
];
const NUMBER_0: &[Cmd] = &[
    Cmd::Move(21.0, 12.0),
    Cmd::Cubic(21.0, 16.97056, 16.97056, 21.0, 12.0, 21.0),
    Cmd::Cubic(7.02944, 21.0, 3.0, 16.97056, 3.0, 12.0),
    Cmd::Cubic(3.0, 7.02944, 7.02944, 3.0, 12.0, 3.0),
    Cmd::Cubic(16.97056, 3.0, 21.0, 7.02944, 21.0, 12.0),
    Cmd::Close,
];
const NUMBER_1: &[Cmd] = &[
    Cmd::Move(10.2, 9.7),
    Cmd::Line(12.6, 8.0),
    Cmd::Line(12.6, 16.0),
];
const MOSAIC_0: &[Cmd] = &[
    Cmd::Move(4.7, 3.5),
    Cmd::Line(7.3, 3.5),
    Cmd::Cubic(7.96274, 3.5, 8.5, 4.03726, 8.5, 4.7),
    Cmd::Line(8.5, 7.3),
    Cmd::Cubic(8.5, 7.96274, 7.96274, 8.5, 7.3, 8.5),
    Cmd::Line(4.7, 8.5),
    Cmd::Cubic(4.03726, 8.5, 3.5, 7.96274, 3.5, 7.3),
    Cmd::Line(3.5, 4.7),
    Cmd::Cubic(3.5, 4.03726, 4.03726, 3.5, 4.7, 3.5),
    Cmd::Close,
];
const MOSAIC_1: &[Cmd] = &[
    Cmd::Move(16.7, 3.5),
    Cmd::Line(19.3, 3.5),
    Cmd::Cubic(19.96274, 3.5, 20.5, 4.03726, 20.5, 4.7),
    Cmd::Line(20.5, 7.3),
    Cmd::Cubic(20.5, 7.96274, 19.96274, 8.5, 19.3, 8.5),
    Cmd::Line(16.7, 8.5),
    Cmd::Cubic(16.03726, 8.5, 15.5, 7.96274, 15.5, 7.3),
    Cmd::Line(15.5, 4.7),
    Cmd::Cubic(15.5, 4.03726, 16.03726, 3.5, 16.7, 3.5),
    Cmd::Close,
];
const MOSAIC_2: &[Cmd] = &[
    Cmd::Move(10.7, 9.5),
    Cmd::Line(13.3, 9.5),
    Cmd::Cubic(13.96274, 9.5, 14.5, 10.03726, 14.5, 10.7),
    Cmd::Line(14.5, 13.3),
    Cmd::Cubic(14.5, 13.96274, 13.96274, 14.5, 13.3, 14.5),
    Cmd::Line(10.7, 14.5),
    Cmd::Cubic(10.03726, 14.5, 9.5, 13.96274, 9.5, 13.3),
    Cmd::Line(9.5, 10.7),
    Cmd::Cubic(9.5, 10.03726, 10.03726, 9.5, 10.7, 9.5),
    Cmd::Close,
];
const MOSAIC_3: &[Cmd] = &[
    Cmd::Move(4.7, 15.5),
    Cmd::Line(7.3, 15.5),
    Cmd::Cubic(7.96274, 15.5, 8.5, 16.03726, 8.5, 16.7),
    Cmd::Line(8.5, 19.3),
    Cmd::Cubic(8.5, 19.96274, 7.96274, 20.5, 7.3, 20.5),
    Cmd::Line(4.7, 20.5),
    Cmd::Cubic(4.03726, 20.5, 3.5, 19.96274, 3.5, 19.3),
    Cmd::Line(3.5, 16.7),
    Cmd::Cubic(3.5, 16.03726, 4.03726, 15.5, 4.7, 15.5),
    Cmd::Close,
];
const MOSAIC_4: &[Cmd] = &[
    Cmd::Move(16.7, 15.5),
    Cmd::Line(19.3, 15.5),
    Cmd::Cubic(19.96274, 15.5, 20.5, 16.03726, 20.5, 16.7),
    Cmd::Line(20.5, 19.3),
    Cmd::Cubic(20.5, 19.96274, 19.96274, 20.5, 19.3, 20.5),
    Cmd::Line(16.7, 20.5),
    Cmd::Cubic(16.03726, 20.5, 15.5, 19.96274, 15.5, 19.3),
    Cmd::Line(15.5, 16.7),
    Cmd::Cubic(15.5, 16.03726, 16.03726, 15.5, 16.7, 15.5),
    Cmd::Close,
];
const MOSAIC_5: &[Cmd] = &[
    Cmd::Move(10.7, 3.5),
    Cmd::Line(13.3, 3.5),
    Cmd::Cubic(13.96274, 3.5, 14.5, 4.03726, 14.5, 4.7),
    Cmd::Line(14.5, 7.3),
    Cmd::Cubic(14.5, 7.96274, 13.96274, 8.5, 13.3, 8.5),
    Cmd::Line(10.7, 8.5),
    Cmd::Cubic(10.03726, 8.5, 9.5, 7.96274, 9.5, 7.3),
    Cmd::Line(9.5, 4.7),
    Cmd::Cubic(9.5, 4.03726, 10.03726, 3.5, 10.7, 3.5),
    Cmd::Close,
];
const MOSAIC_6: &[Cmd] = &[
    Cmd::Move(4.7, 9.5),
    Cmd::Line(7.3, 9.5),
    Cmd::Cubic(7.96274, 9.5, 8.5, 10.03726, 8.5, 10.7),
    Cmd::Line(8.5, 13.3),
    Cmd::Cubic(8.5, 13.96274, 7.96274, 14.5, 7.3, 14.5),
    Cmd::Line(4.7, 14.5),
    Cmd::Cubic(4.03726, 14.5, 3.5, 13.96274, 3.5, 13.3),
    Cmd::Line(3.5, 10.7),
    Cmd::Cubic(3.5, 10.03726, 4.03726, 9.5, 4.7, 9.5),
    Cmd::Close,
];
const MOSAIC_7: &[Cmd] = &[
    Cmd::Move(16.7, 9.5),
    Cmd::Line(19.3, 9.5),
    Cmd::Cubic(19.96274, 9.5, 20.5, 10.03726, 20.5, 10.7),
    Cmd::Line(20.5, 13.3),
    Cmd::Cubic(20.5, 13.96274, 19.96274, 14.5, 19.3, 14.5),
    Cmd::Line(16.7, 14.5),
    Cmd::Cubic(16.03726, 14.5, 15.5, 13.96274, 15.5, 13.3),
    Cmd::Line(15.5, 10.7),
    Cmd::Cubic(15.5, 10.03726, 16.03726, 9.5, 16.7, 9.5),
    Cmd::Close,
];
const MOSAIC_8: &[Cmd] = &[
    Cmd::Move(10.7, 15.5),
    Cmd::Line(13.3, 15.5),
    Cmd::Cubic(13.96274, 15.5, 14.5, 16.03726, 14.5, 16.7),
    Cmd::Line(14.5, 19.3),
    Cmd::Cubic(14.5, 19.96274, 13.96274, 20.5, 13.3, 20.5),
    Cmd::Line(10.7, 20.5),
    Cmd::Cubic(10.03726, 20.5, 9.5, 19.96274, 9.5, 19.3),
    Cmd::Line(9.5, 16.7),
    Cmd::Cubic(9.5, 16.03726, 10.03726, 15.5, 10.7, 15.5),
    Cmd::Close,
];
const UNDO_0: &[Cmd] = &[
    Cmd::Move(8.5, 4.5),
    Cmd::Line(4.0, 9.0),
    Cmd::Line(8.5, 13.5),
    Cmd::Move(4.0, 9.0),
    Cmd::Line(14.25, 9.0),
    Cmd::Cubic(17.14949, 9.0, 19.5, 11.35051, 19.5, 14.25),
    Cmd::Cubic(19.5, 17.14949, 17.14949, 19.5, 14.25, 19.5),
    Cmd::Line(10.0, 19.5),
];
const REDO_0: &[Cmd] = &[
    Cmd::Move(15.5, 4.5),
    Cmd::Line(20.0, 9.0),
    Cmd::Line(15.5, 13.5),
    Cmd::Move(20.0, 9.0),
    Cmd::Line(9.75, 9.0),
    Cmd::Cubic(6.85051, 9.0, 4.5, 11.35051, 4.5, 14.25),
    Cmd::Cubic(4.5, 17.14949, 6.85051, 19.5, 9.75, 19.5),
    Cmd::Line(14.0, 19.5),
];
const LONG_0: &[Cmd] = &[
    Cmd::Move(4.0, 9.5),
    Cmd::Line(4.0, 6.0),
    Cmd::Cubic(4.0, 4.61929, 5.11929, 3.5, 6.5, 3.5),
    Cmd::Line(17.5, 3.5),
    Cmd::Cubic(18.88071, 3.5, 20.0, 4.61929, 20.0, 6.0),
    Cmd::Line(20.0, 9.5),
    Cmd::Move(4.0, 18.0),
    Cmd::Cubic(4.0, 19.38071, 5.11929, 20.5, 6.5, 20.5),
    Cmd::Line(17.5, 20.5),
    Cmd::Cubic(18.88071, 20.5, 20.0, 19.38071, 20.0, 18.0),
    Cmd::Move(4.0, 12.9),
    Cmd::Line(4.0, 14.6),
    Cmd::Move(20.0, 12.9),
    Cmd::Line(20.0, 14.6),
    Cmd::Move(12.0, 7.5),
    Cmd::Line(12.0, 16.5),
    Cmd::Move(8.5, 13.0),
    Cmd::Line(12.0, 16.5),
    Cmd::Line(15.5, 13.0),
];
const SAVE_0: &[Cmd] = &[
    Cmd::Move(6.0, 3.5),
    Cmd::Line(16.2, 3.5),
    Cmd::Line(20.5, 7.8),
    Cmd::Line(20.5, 18.0),
    Cmd::Cubic(20.5, 19.38071, 19.38071, 20.5, 18.0, 20.5),
    Cmd::Line(6.0, 20.5),
    Cmd::Cubic(4.61929, 20.5, 3.5, 19.38071, 3.5, 18.0),
    Cmd::Line(3.5, 6.0),
    Cmd::Cubic(3.5, 4.61929, 4.61929, 3.5, 6.0, 3.5),
    Cmd::Close,
    Cmd::Move(7.5, 3.5),
    Cmd::Line(7.5, 8.0),
    Cmd::Line(14.5, 8.0),
    Cmd::Line(14.5, 3.5),
    Cmd::Move(7.0, 20.5),
    Cmd::Line(7.0, 14.0),
    Cmd::Line(17.0, 14.0),
    Cmd::Line(17.0, 20.5),
];
const CANCEL_0: &[Cmd] = &[
    Cmd::Move(5.5, 5.5),
    Cmd::Line(18.5, 18.5),
    Cmd::Move(18.5, 5.5),
    Cmd::Line(5.5, 18.5),
];
const DONE_0: &[Cmd] = &[
    Cmd::Move(4.5, 12.5),
    Cmd::Line(9.5, 17.5),
    Cmd::Line(19.5, 6.5),
];
const FONT1_0: &[Cmd] = &[
    Cmd::Move(8.75, 9.69),
    Cmd::Line(8.75, 8.5),
    Cmd::Line(15.25, 8.5),
    Cmd::Line(15.25, 9.69),
    Cmd::Move(12.0, 8.5),
    Cmd::Line(12.0, 15.5),
    Cmd::Move(10.635, 15.5),
    Cmd::Line(13.365, 15.5),
];
const FONT2_0: &[Cmd] = &[
    Cmd::Move(7.75, 8.87),
    Cmd::Line(7.75, 7.25),
    Cmd::Line(16.25, 7.25),
    Cmd::Line(16.25, 8.87),
    Cmd::Move(12.0, 7.25),
    Cmd::Line(12.0, 16.75),
    Cmd::Move(10.215, 16.75),
    Cmd::Line(13.785, 16.75),
];
const FONT3_0: &[Cmd] = &[
    Cmd::Move(6.5, 8.04),
    Cmd::Line(6.5, 6.0),
    Cmd::Line(17.5, 6.0),
    Cmd::Line(17.5, 8.04),
    Cmd::Move(12.0, 6.0),
    Cmd::Line(12.0, 18.0),
    Cmd::Move(9.69, 18.0),
    Cmd::Line(14.31, 18.0),
];
const FONT4_0: &[Cmd] = &[
    Cmd::Move(5.25, 7.22),
    Cmd::Line(5.25, 4.75),
    Cmd::Line(18.75, 4.75),
    Cmd::Line(18.75, 7.22),
    Cmd::Move(12.0, 4.75),
    Cmd::Line(12.0, 19.25),
    Cmd::Move(9.165, 19.25),
    Cmd::Line(14.835, 19.25),
];
const FONT5_0: &[Cmd] = &[
    Cmd::Move(4.0, 6.39),
    Cmd::Line(4.0, 3.5),
    Cmd::Line(20.0, 3.5),
    Cmd::Line(20.0, 6.39),
    Cmd::Move(12.0, 3.5),
    Cmd::Line(12.0, 20.5),
    Cmd::Move(8.64, 20.5),
    Cmd::Line(15.36, 20.5),
];

/// Every icon, in the order of the data file.
pub const ICONS: &[Icon] = &[
    Icon {
        key: "select",
        name: "Select",
        parts: &[
            Part { paint: Paint::FillAndStroke, width: 1.0, opacity: 1.0, cmds: SELECT_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 9, y: 7, w: 10, h: 14, count: 79 },
            Ink { scale: 1.5, cell: 42, x: 13, y: 10, w: 16, h: 22, count: 184 },
            Ink { scale: 2.0, cell: 56, x: 18, y: 13, w: 20, h: 30, count: 315 },
        ],
    },
    Icon {
        key: "rect",
        name: "Rectangle",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: RECT_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 7, w: 16, h: 14, count: 84 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 11, w: 22, h: 20, count: 144 },
            Ink { scale: 2.0, cell: 56, x: 13, y: 15, w: 30, h: 26, count: 276 },
        ],
    },
    Icon {
        key: "ellipse",
        name: "Ellipse",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: ELLIPSE_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 7, w: 16, h: 14, count: 60 },
            Ink { scale: 1.5, cell: 42, x: 9, y: 10, w: 24, h: 22, count: 152 },
            Ink { scale: 2.0, cell: 56, x: 11, y: 14, w: 34, h: 28, count: 268 },
        ],
    },
    Icon {
        key: "line",
        name: "Straight Line",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: LINE_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 8, y: 8, w: 12, h: 12, count: 34 },
            Ink { scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 58 },
            Ink { scale: 2.0, cell: 56, x: 15, y: 15, w: 26, h: 26, count: 124 },
        ],
    },
    Icon {
        key: "arrow",
        name: "Arrow",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: ARROW_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 8, y: 7, w: 13, h: 13, count: 60 },
            Ink { scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 100 },
            Ink { scale: 2.0, cell: 56, x: 15, y: 15, w: 26, h: 26, count: 200 },
        ],
    },
    Icon {
        key: "pen",
        name: "Pen",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: PEN_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 7, y: 6, w: 15, h: 15, count: 84 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 9, w: 23, h: 23, count: 174 },
            Ink { scale: 2.0, cell: 56, x: 13, y: 12, w: 31, h: 31, count: 291 },
        ],
    },
    Icon {
        key: "highlighter",
        name: "Highlighter",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: HIGHLIGHTER_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 17, count: 95 },
            Ink { scale: 1.5, cell: 42, x: 9, y: 9, w: 25, h: 25, count: 195 },
            Ink { scale: 2.0, cell: 56, x: 12, y: 13, w: 33, h: 32, count: 352 },
        ],
    },
    Icon {
        key: "text",
        name: "Text",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: TEXT_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 64 },
            Ink { scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 104 },
            Ink { scale: 2.0, cell: 56, x: 15, y: 15, w: 26, h: 26, count: 216 },
        ],
    },
    Icon {
        key: "number",
        name: "Number",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: NUMBER_0 },
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: NUMBER_1 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 73 },
            Ink { scale: 1.5, cell: 42, x: 9, y: 9, w: 24, h: 24, count: 184 },
            Ink { scale: 2.0, cell: 56, x: 11, y: 11, w: 34, h: 34, count: 357 },
        ],
    },
    Icon {
        key: "mosaic",
        name: "Mosaic",
        parts: &[
            Part { paint: Paint::Fill, width: 0.0, opacity: 1.0, cmds: MOSAIC_0 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 1.0, cmds: MOSAIC_1 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 1.0, cmds: MOSAIC_2 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 1.0, cmds: MOSAIC_3 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 1.0, cmds: MOSAIC_4 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 0.38, cmds: MOSAIC_5 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 0.38, cmds: MOSAIC_6 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 0.38, cmds: MOSAIC_7 },
            Part { paint: Paint::Fill, width: 0.0, opacity: 0.38, cmds: MOSAIC_8 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 80 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 10, w: 22, h: 22, count: 216 },
            Ink { scale: 2.0, cell: 56, x: 14, y: 14, w: 28, h: 28, count: 320 },
        ],
    },
    Icon {
        key: "undo",
        name: "Undo",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: UNDO_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 57 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 11, w: 22, h: 21, count: 124 },
            Ink { scale: 2.0, cell: 56, x: 13, y: 14, w: 29, h: 28, count: 233 },
        ],
    },
    Icon {
        key: "redo",
        name: "Redo",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: REDO_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 57 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 11, w: 22, h: 21, count: 124 },
            Ink { scale: 2.0, cell: 56, x: 14, y: 14, w: 29, h: 28, count: 233 },
        ],
    },
    Icon {
        key: "long",
        name: "Long Screenshot",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: LONG_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 104 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 9, w: 22, h: 24, count: 220 },
            Ink { scale: 2.0, cell: 56, x: 13, y: 12, w: 30, h: 32, count: 378 },
        ],
    },
    Icon {
        key: "save",
        name: "Save",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: SAVE_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 150 },
            Ink { scale: 1.5, cell: 42, x: 9, y: 9, w: 24, h: 24, count: 318 },
            Ink { scale: 2.0, cell: 56, x: 12, y: 12, w: 32, h: 32, count: 485 },
        ],
    },
    Icon {
        key: "cancel",
        name: "Cancel",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: CANCEL_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 8, y: 8, w: 12, h: 12, count: 64 },
            Ink { scale: 1.5, cell: 42, x: 12, y: 12, w: 18, h: 18, count: 100 },
            Ink { scale: 2.0, cell: 56, x: 16, y: 16, w: 24, h: 24, count: 216 },
        ],
    },
    Icon {
        key: "done",
        name: "Done",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: DONE_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 7, y: 9, w: 14, h: 10, count: 28 },
            Ink { scale: 1.5, cell: 42, x: 11, y: 13, w: 20, h: 16, count: 63 },
            Ink { scale: 2.0, cell: 56, x: 14, y: 17, w: 28, h: 22, count: 113 },
        ],
    },
    Icon {
        key: "font1",
        name: "Font Size",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: FONT1_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 10, y: 10, w: 8, h: 8, count: 30 },
            Ink { scale: 1.5, cell: 42, x: 16, y: 15, w: 10, h: 12, count: 58 },
            Ink { scale: 2.0, cell: 56, x: 21, y: 21, w: 14, h: 14, count: 104 },
        ],
    },
    Icon {
        key: "font2",
        name: "Font Size",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: FONT2_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 10, y: 9, w: 8, h: 10, count: 38 },
            Ink { scale: 1.5, cell: 42, x: 14, y: 14, w: 14, h: 14, count: 68 },
            Ink { scale: 2.0, cell: 56, x: 19, y: 19, w: 18, h: 19, count: 138 },
        ],
    },
    Icon {
        key: "font3",
        name: "Font Size",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: FONT3_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 9, y: 8, w: 10, h: 12, count: 46 },
            Ink { scale: 1.5, cell: 42, x: 13, y: 12, w: 16, h: 18, count: 98 },
            Ink { scale: 2.0, cell: 56, x: 17, y: 16, w: 22, h: 24, count: 198 },
        ],
    },
    Icon {
        key: "font4",
        name: "Font Size",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: FONT4_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 8, y: 7, w: 12, h: 14, count: 60 },
            Ink { scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 104 },
            Ink { scale: 2.0, cell: 56, x: 15, y: 14, w: 26, h: 28, count: 238 },
        ],
    },
    Icon {
        key: "font5",
        name: "Font Size",
        parts: &[
            Part { paint: Paint::Stroke, width: 1.75, opacity: 1.0, cmds: FONT5_0 },
        ],
        ink: &[
            Ink { scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 72 },
            Ink { scale: 1.5, cell: 42, x: 10, y: 9, w: 22, h: 24, count: 142 },
            Ink { scale: 2.0, cell: 56, x: 13, y: 12, w: 30, h: 32, count: 260 },
        ],
    },
];

pub const TOOLBAR_ICONS: [&str; 16] = ["select", "rect", "ellipse", "line", "arrow", "pen", "highlighter", "text", "number", "mosaic", "undo", "redo", "long", "save", "cancel", "done"];
pub const FONT_ICONS: [&str; 5] = ["font1", "font2", "font3", "font4", "font5"];

/// The icon called `key`, if there is one.
pub fn icon(key: &str) -> Option<&'static Icon> {
    ICONS.iter().find(|i| i.key == key)
}
