// swiftlint:disable all
//
// GENERATED. Do not edit this file. It is written from
// `src/input/screenshot-look.json` by `python3 tools/gen-screenshot-look.py --write`;
// change the data and run that. `tools/the-screenshot-look-is-one-set.py`
// fails when this file is not what the data says. The Windows host has the
// same data as `windows/shots/src/look.rs`, written by the same run.

import Foundation

/// What the screenshot overlay looks like: sizes, colours, durations and
/// the icons' paths (`dev-docs/poltergeist/screenshot.md`, 9.8). Lengths are
/// logical points unless a name says otherwise.
enum ShotLook {
    /// A colour and how much of it there is.
    struct RGBA: Equatable {
        var r: UInt8
        var g: UInt8
        var b: UInt8
        /// 0 to 1.
        var a: Double
    }

    /// One step of a path, in units of the icon's artboard.
    enum Cmd: Equatable {
        case move(Double, Double)
        case line(Double, Double)
        /// Two control points and the end.
        case cubic(Double, Double, Double, Double, Double, Double)
        case close
    }

    enum Paint: Equatable {
        case stroke
        case fill
        /// Filled, and stroked in the same colour to round its corners.
        case fillAndStroke
    }

    /// One shape of an icon. Parts are drawn in order, one over another.
    struct Part: Equatable {
        var paint: Paint
        /// The stroke's width in artboard units; 0 for a fill.
        var width: Double
        var opacity: Double
        var cmds: [Cmd]
    }

    /// Where an icon's ink is when it is drawn into a button cell: the box
    /// of the pixels at least half covered, and how many there are.
    struct Ink: Equatable {
        var scale: Double
        /// The cell's side in pixels.
        var cell: Int
        var x: Int
        var y: Int
        var w: Int
        var h: Int
        var count: Int
    }

    struct Icon: Equatable {
        var key: String
        /// The English name, a msgid of `src/input/screenshot.zig`.
        var name: String
        var parts: [Part]
        /// What the generator's own rasteriser made of it; the test of
        /// `ShotIconRaster` is that it makes the same.
        var ink: [Ink]
    }

    /// The grid the icons are drawn on.
    enum IconGrid {
        static let artboard: Double = 24.0
        static let liveMin: Double = 2.0
        static let liveMax: Double = 22.0
        static let stroke: Double = 1.75
        static let points: Double = 20.0
    }

    enum Size {
        static let button: Double = 28.0
        static let gap: Double = 4.0
        static let groupGap: Double = 12.0
        static let padding: Double = 6.0
        static let rowGap: Double = 0.0
        static let rowDivider: Double = 0.5
        static let plateRadius: Double = 12.0
        static let cellRadius: Double = 7.0
        static let icon: Double = 20.0
        static let swatch: Double = 16.0
        static let swatchEdge: Double = 0.5
        static let hoverEdge: Double = 0.5
        static let ring: Double = 1.5
        static let glowSigma: Double = 2.0
        static let offset: Double = 8.0
        static let plateShadowDy: Double = 4.0
        static let plateShadowSigma: Double = 7.0
        static let plateEdge: Double = 0.5
        static let labelRadius: Double = 8.0
        static let tipPadX: Double = 10.0
        static let tipPadY: Double = 6.0
        static let tipKeyGap: Double = 8.0
        static let tipKeyPadX: Double = 5.0
        static let tipKeyPadY: Double = 2.0
        static let tipKeyRadius: Double = 4.0
        static let tipOffset: Double = 4.0
        static let statusPadX: Double = 10.0
        static let statusPadY: Double = 6.0
        static let statusDot: Double = 8.0
        static let statusDotHalo: Double = 3.0
        static let statusGap: Double = 8.0
        static let sizeLabelPadX: Double = 8.0
        static let sizeLabelPadY: Double = 5.0
        static let sizeLabelOffset: Double = 6.0
        static let sizeLabelInset: Double = 4.0
        static let selectionLine: Double = 1.0
        static let selectionKnob: Double = 7.0
        static let windowLine: Double = 2.0
        static let mosaicFrame: Double = 16.0
        static let mosaicFrameLine: Double = 1.0
    }

    enum Glass {
        static let plateBlurSigma: Double = 12.0
        static let plateSaturation: Double = 1.5
        static let plateBrightness: Double = 0.5
        static let outsideBlurSigma: Double = 3.0
        static let lumaR: Double = 0.2126
        static let lumaG: Double = 0.7152
        static let lumaB: Double = 0.0722
        static let downsampleScaleAtLeast: Double = 1.75
        static let downsampleHi: Double = 4.0
        static let downsampleLo: Double = 2.0
        static let boxPasses: Double = 3.0
        static let waitMs: Double = 50.0
    }

    enum TransitionMs {
        static let hoverIn: Double = 80.0
        static let hoverOut: Double = 120.0
        static let press: Double = 0.0
        static let release: Double = 120.0
        static let deselect: Double = 100.0
        static let windowSwitch: Double = 120.0
        static let dragStart: Double = 120.0
        static let gripHover: Double = 80.0
        static let tipDelay: Double = 500.0
    }

    enum TextBox {
        static let line: Double = 1.0
        static let dash: Double = 4.0
        static let offset: Double = 2.0
        static let caretWidth: Double = 2.0
        static let caretHeightEm: Double = 1.08
        static let caretEdge: Double = 1.0
        static let haloNearSigma: Double = 0.5
        static let haloNearAlpha: Double = 0.85
        static let haloFarSigma: Double = 1.25
        static let haloFarAlpha: Double = 0.55
        static let markedLine: Double = 2.0
        static let lightTextLuminance: Double = 0.5
        static let selectionAlpha: Double = 0.35
    }

    enum Annotation {
        static let frameOffset: Double = 4.0
        static let frameLine: Double = 1.0
        static let frameDashOn: Double = 4.0
        static let frameDashOff: Double = 3.0
        static let frameRadius: Double = 2.0
        static let grip: Double = 7.0
        static let gripHot: Double = 9.0
        static let gripRadius: Double = 1.5
        static let gripLine: Double = 1.0
        static let gripShadow: Double = 0.6
        static let gripReach: Double = 6.0
        static let outsideOpacity: Double = 0.4
        static let tagOffset: Double = 12.0
        static let dragThreshold: Double = 3.0
        static let dirtyRing: Double = 5.0
        static let dirtyShadowX: Double = 14.0
        static let dirtyShadowTop: Double = 10.0
        static let dirtyShadowBottom: Double = 18.0
    }

    enum Levels {
        static let dots: [Double] = [3.0, 5.0, 8.0, 11.0, 15.0]
        static let mosaicCells: [Double] = [6.0, 5.0, 4.0, 3.0, 2.0]
    }

    enum Colour {
        static let plateTint = RGBA(r: 0x1D, g: 0x1F, b: 0x20, a: 0.66)
        static let plateOpaque = RGBA(r: 0x3D, g: 0x3F, b: 0x40, a: 1.0)
        static let plateOpaqueEdge = RGBA(r: 0x8E, g: 0x8F, b: 0x90, a: 1.0)
        static let plateInnerEdge = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.22)
        static let plateOuterEdge = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.35)
        static let plateShadow = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.3)
        static let rowDivider = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.18)
        static let ink = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0)
        static let inkDim = RGBA(r: 0xA0, g: 0xA0, b: 0xA0, a: 1.0)
        static let inkOff = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.32)
        static let hover = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.14)
        static let hoverEdge = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.3)
        static let down = RGBA(r: 0x41, g: 0x9C, b: 0xFF, a: 0.18)
        static let accent = RGBA(r: 0x41, g: 0x9C, b: 0xFF, a: 1.0)
        static let glow = RGBA(r: 0x41, g: 0x9C, b: 0xFF, a: 0.4)
        static let doneDownInk = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0)
        static let swatchEdge = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.3)
        static let tipKeyPlate = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.12)
        static let mosaicFrame = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.45)
        static let statusDot = RGBA(r: 0xE0, g: 0x40, b: 0x40, a: 1.0)
        static let statusDotHalo = RGBA(r: 0xE0, g: 0x40, b: 0x40, a: 0.3)
        static let outsideDim = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.06)
        static let outsideDimOpaque = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.43)
        static let knobFill = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0)
        static let boxDark = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.72)
        static let boxLight = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.95)
        static let caretEdgeDark = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.6)
        static let caretEdgeLight = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.75)
        static let frameLight = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 0.85)
        static let gripFill = RGBA(r: 0xFF, g: 0xFF, b: 0xFF, a: 1.0)
        static let gripShadow = RGBA(r: 0x00, g: 0x00, b: 0x00, a: 0.6)
    }

    /// Every icon, in the order of the data file.
    static let icons: [Icon] = [
        Icon(
            key: "select",
            name: "Select",
            parts: [
                Part(paint: .fillAndStroke, width: 1.0, opacity: 1.0, cmds: [
                    .move(6.4, 3.4),
                    .line(6.4, 18.2),
                    .line(10.0, 14.9),
                    .line(12.6, 20.6),
                    .line(15.0, 19.6),
                    .line(12.5, 14.0),
                    .line(17.6, 14.0),
                    .close,
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 9, y: 7, w: 10, h: 14, count: 79),
                Ink(scale: 1.5, cell: 42, x: 13, y: 10, w: 16, h: 22, count: 184),
                Ink(scale: 2.0, cell: 56, x: 18, y: 13, w: 20, h: 30, count: 315),
            ]),
        Icon(
            key: "rect",
            name: "Rectangle",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(6.5, 5.0),
                    .line(17.5, 5.0),
                    .cubic(18.88071, 5.0, 20.0, 6.11929, 20.0, 7.5),
                    .line(20.0, 16.5),
                    .cubic(20.0, 17.88071, 18.88071, 19.0, 17.5, 19.0),
                    .line(6.5, 19.0),
                    .cubic(5.11929, 19.0, 4.0, 17.88071, 4.0, 16.5),
                    .line(4.0, 7.5),
                    .cubic(4.0, 6.11929, 5.11929, 5.0, 6.5, 5.0),
                    .close,
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 6, y: 7, w: 16, h: 14, count: 84),
                Ink(scale: 1.5, cell: 42, x: 10, y: 11, w: 22, h: 20, count: 144),
                Ink(scale: 2.0, cell: 56, x: 13, y: 15, w: 30, h: 26, count: 276),
            ]),
        Icon(
            key: "ellipse",
            name: "Ellipse",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(21.0, 12.0),
                    .cubic(21.0, 16.28021, 16.97056, 19.75, 12.0, 19.75),
                    .cubic(7.02944, 19.75, 3.0, 16.28021, 3.0, 12.0),
                    .cubic(3.0, 7.71979, 7.02944, 4.25, 12.0, 4.25),
                    .cubic(16.97056, 4.25, 21.0, 7.71979, 21.0, 12.0),
                    .close,
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 6, y: 7, w: 16, h: 14, count: 60),
                Ink(scale: 1.5, cell: 42, x: 9, y: 10, w: 24, h: 22, count: 152),
                Ink(scale: 2.0, cell: 56, x: 11, y: 14, w: 34, h: 28, count: 268),
            ]),
        Icon(
            key: "line",
            name: "Straight Line",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(5.0, 19.0),
                    .line(19.0, 5.0),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 8, y: 8, w: 12, h: 12, count: 34),
                Ink(scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 58),
                Ink(scale: 2.0, cell: 56, x: 15, y: 15, w: 26, h: 26, count: 124),
            ]),
        Icon(
            key: "arrow",
            name: "Arrow",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(5.0, 19.0),
                    .line(19.0, 5.0),
                    .move(10.5, 5.0),
                    .line(19.0, 5.0),
                    .line(19.0, 13.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 8, y: 7, w: 13, h: 13, count: 60),
                Ink(scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 100),
                Ink(scale: 2.0, cell: 56, x: 15, y: 15, w: 26, h: 26, count: 200),
            ]),
        Icon(
            key: "pen",
            name: "Pen",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(4.0, 20.0),
                    .line(5.1, 15.3),
                    .line(16.4, 4.0),
                    .cubic(17.16063, 3.24361, 18.38937, 3.24361, 19.15, 4.0),
                    .line(20.0, 4.85),
                    .cubic(20.75639, 5.61063, 20.75639, 6.83937, 20.0, 7.6),
                    .line(8.7, 18.9),
                    .close,
                    .move(14.4, 6.0),
                    .line(18.0, 9.6),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 7, y: 6, w: 15, h: 15, count: 84),
                Ink(scale: 1.5, cell: 42, x: 10, y: 9, w: 23, h: 23, count: 174),
                Ink(scale: 2.0, cell: 56, x: 13, y: 12, w: 31, h: 31, count: 291),
            ]),
        Icon(
            key: "highlighter",
            name: "Highlighter",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(9.2, 12.6),
                    .line(16.0, 4.2),
                    .cubic(16.52698, 3.56924, 17.46343, 3.48006, 18.1, 4.0),
                    .line(20.7, 6.1),
                    .cubic(21.33076, 6.62698, 21.41994, 7.56343, 20.9, 8.2),
                    .line(14.1, 16.6),
                    .close,
                    .move(9.2, 12.6),
                    .line(8.2, 16.1),
                    .line(10.6, 18.0),
                    .line(14.1, 16.6),
                    .move(8.2, 16.1),
                    .line(5.6, 19.3),
                    .line(9.8, 19.3),
                    .line(10.6, 18.0),
                    .move(3.5, 21.5),
                    .line(20.5, 21.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 17, count: 95),
                Ink(scale: 1.5, cell: 42, x: 9, y: 9, w: 25, h: 25, count: 195),
                Ink(scale: 2.0, cell: 56, x: 12, y: 13, w: 33, h: 32, count: 352),
            ]),
        Icon(
            key: "text",
            name: "Text",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(5.0, 7.5),
                    .line(5.0, 5.0),
                    .line(19.0, 5.0),
                    .line(19.0, 7.5),
                    .move(12.0, 5.0),
                    .line(12.0, 19.0),
                    .move(9.0, 19.0),
                    .line(15.0, 19.0),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 64),
                Ink(scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 104),
                Ink(scale: 2.0, cell: 56, x: 15, y: 15, w: 26, h: 26, count: 216),
            ]),
        Icon(
            key: "number",
            name: "Number",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(21.0, 12.0),
                    .cubic(21.0, 16.97056, 16.97056, 21.0, 12.0, 21.0),
                    .cubic(7.02944, 21.0, 3.0, 16.97056, 3.0, 12.0),
                    .cubic(3.0, 7.02944, 7.02944, 3.0, 12.0, 3.0),
                    .cubic(16.97056, 3.0, 21.0, 7.02944, 21.0, 12.0),
                    .close,
                ]),
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(10.2, 9.7),
                    .line(12.6, 8.0),
                    .line(12.6, 16.0),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 73),
                Ink(scale: 1.5, cell: 42, x: 9, y: 9, w: 24, h: 24, count: 184),
                Ink(scale: 2.0, cell: 56, x: 11, y: 11, w: 34, h: 34, count: 357),
            ]),
        Icon(
            key: "mosaic",
            name: "Mosaic",
            parts: [
                Part(paint: .fill, width: 0.0, opacity: 1.0, cmds: [
                    .move(4.7, 3.5),
                    .line(7.3, 3.5),
                    .cubic(7.96274, 3.5, 8.5, 4.03726, 8.5, 4.7),
                    .line(8.5, 7.3),
                    .cubic(8.5, 7.96274, 7.96274, 8.5, 7.3, 8.5),
                    .line(4.7, 8.5),
                    .cubic(4.03726, 8.5, 3.5, 7.96274, 3.5, 7.3),
                    .line(3.5, 4.7),
                    .cubic(3.5, 4.03726, 4.03726, 3.5, 4.7, 3.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 1.0, cmds: [
                    .move(16.7, 3.5),
                    .line(19.3, 3.5),
                    .cubic(19.96274, 3.5, 20.5, 4.03726, 20.5, 4.7),
                    .line(20.5, 7.3),
                    .cubic(20.5, 7.96274, 19.96274, 8.5, 19.3, 8.5),
                    .line(16.7, 8.5),
                    .cubic(16.03726, 8.5, 15.5, 7.96274, 15.5, 7.3),
                    .line(15.5, 4.7),
                    .cubic(15.5, 4.03726, 16.03726, 3.5, 16.7, 3.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 1.0, cmds: [
                    .move(10.7, 9.5),
                    .line(13.3, 9.5),
                    .cubic(13.96274, 9.5, 14.5, 10.03726, 14.5, 10.7),
                    .line(14.5, 13.3),
                    .cubic(14.5, 13.96274, 13.96274, 14.5, 13.3, 14.5),
                    .line(10.7, 14.5),
                    .cubic(10.03726, 14.5, 9.5, 13.96274, 9.5, 13.3),
                    .line(9.5, 10.7),
                    .cubic(9.5, 10.03726, 10.03726, 9.5, 10.7, 9.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 1.0, cmds: [
                    .move(4.7, 15.5),
                    .line(7.3, 15.5),
                    .cubic(7.96274, 15.5, 8.5, 16.03726, 8.5, 16.7),
                    .line(8.5, 19.3),
                    .cubic(8.5, 19.96274, 7.96274, 20.5, 7.3, 20.5),
                    .line(4.7, 20.5),
                    .cubic(4.03726, 20.5, 3.5, 19.96274, 3.5, 19.3),
                    .line(3.5, 16.7),
                    .cubic(3.5, 16.03726, 4.03726, 15.5, 4.7, 15.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 1.0, cmds: [
                    .move(16.7, 15.5),
                    .line(19.3, 15.5),
                    .cubic(19.96274, 15.5, 20.5, 16.03726, 20.5, 16.7),
                    .line(20.5, 19.3),
                    .cubic(20.5, 19.96274, 19.96274, 20.5, 19.3, 20.5),
                    .line(16.7, 20.5),
                    .cubic(16.03726, 20.5, 15.5, 19.96274, 15.5, 19.3),
                    .line(15.5, 16.7),
                    .cubic(15.5, 16.03726, 16.03726, 15.5, 16.7, 15.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 0.38, cmds: [
                    .move(10.7, 3.5),
                    .line(13.3, 3.5),
                    .cubic(13.96274, 3.5, 14.5, 4.03726, 14.5, 4.7),
                    .line(14.5, 7.3),
                    .cubic(14.5, 7.96274, 13.96274, 8.5, 13.3, 8.5),
                    .line(10.7, 8.5),
                    .cubic(10.03726, 8.5, 9.5, 7.96274, 9.5, 7.3),
                    .line(9.5, 4.7),
                    .cubic(9.5, 4.03726, 10.03726, 3.5, 10.7, 3.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 0.38, cmds: [
                    .move(4.7, 9.5),
                    .line(7.3, 9.5),
                    .cubic(7.96274, 9.5, 8.5, 10.03726, 8.5, 10.7),
                    .line(8.5, 13.3),
                    .cubic(8.5, 13.96274, 7.96274, 14.5, 7.3, 14.5),
                    .line(4.7, 14.5),
                    .cubic(4.03726, 14.5, 3.5, 13.96274, 3.5, 13.3),
                    .line(3.5, 10.7),
                    .cubic(3.5, 10.03726, 4.03726, 9.5, 4.7, 9.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 0.38, cmds: [
                    .move(16.7, 9.5),
                    .line(19.3, 9.5),
                    .cubic(19.96274, 9.5, 20.5, 10.03726, 20.5, 10.7),
                    .line(20.5, 13.3),
                    .cubic(20.5, 13.96274, 19.96274, 14.5, 19.3, 14.5),
                    .line(16.7, 14.5),
                    .cubic(16.03726, 14.5, 15.5, 13.96274, 15.5, 13.3),
                    .line(15.5, 10.7),
                    .cubic(15.5, 10.03726, 16.03726, 9.5, 16.7, 9.5),
                    .close,
                ]),
                Part(paint: .fill, width: 0.0, opacity: 0.38, cmds: [
                    .move(10.7, 15.5),
                    .line(13.3, 15.5),
                    .cubic(13.96274, 15.5, 14.5, 16.03726, 14.5, 16.7),
                    .line(14.5, 19.3),
                    .cubic(14.5, 19.96274, 13.96274, 20.5, 13.3, 20.5),
                    .line(10.7, 20.5),
                    .cubic(10.03726, 20.5, 9.5, 19.96274, 9.5, 19.3),
                    .line(9.5, 16.7),
                    .cubic(9.5, 16.03726, 10.03726, 15.5, 10.7, 15.5),
                    .close,
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 80),
                Ink(scale: 1.5, cell: 42, x: 10, y: 10, w: 22, h: 22, count: 216),
                Ink(scale: 2.0, cell: 56, x: 14, y: 14, w: 28, h: 28, count: 320),
            ]),
        Icon(
            key: "undo",
            name: "Undo",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(8.5, 4.5),
                    .line(4.0, 9.0),
                    .line(8.5, 13.5),
                    .move(4.0, 9.0),
                    .line(14.25, 9.0),
                    .cubic(17.14949, 9.0, 19.5, 11.35051, 19.5, 14.25),
                    .cubic(19.5, 17.14949, 17.14949, 19.5, 14.25, 19.5),
                    .line(10.0, 19.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 57),
                Ink(scale: 1.5, cell: 42, x: 10, y: 11, w: 22, h: 21, count: 124),
                Ink(scale: 2.0, cell: 56, x: 13, y: 14, w: 29, h: 28, count: 233),
            ]),
        Icon(
            key: "redo",
            name: "Redo",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(15.5, 4.5),
                    .line(20.0, 9.0),
                    .line(15.5, 13.5),
                    .move(20.0, 9.0),
                    .line(9.75, 9.0),
                    .cubic(6.85051, 9.0, 4.5, 11.35051, 4.5, 14.25),
                    .cubic(4.5, 17.14949, 6.85051, 19.5, 9.75, 19.5),
                    .line(14.0, 19.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 7, y: 7, w: 14, h: 14, count: 57),
                Ink(scale: 1.5, cell: 42, x: 10, y: 11, w: 22, h: 21, count: 124),
                Ink(scale: 2.0, cell: 56, x: 14, y: 14, w: 29, h: 28, count: 233),
            ]),
        Icon(
            key: "long",
            name: "Long Screenshot",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(4.0, 9.5),
                    .line(4.0, 6.0),
                    .cubic(4.0, 4.61929, 5.11929, 3.5, 6.5, 3.5),
                    .line(17.5, 3.5),
                    .cubic(18.88071, 3.5, 20.0, 4.61929, 20.0, 6.0),
                    .line(20.0, 9.5),
                    .move(4.0, 18.0),
                    .cubic(4.0, 19.38071, 5.11929, 20.5, 6.5, 20.5),
                    .line(17.5, 20.5),
                    .cubic(18.88071, 20.5, 20.0, 19.38071, 20.0, 18.0),
                    .move(4.0, 12.9),
                    .line(4.0, 14.6),
                    .move(20.0, 12.9),
                    .line(20.0, 14.6),
                    .move(12.0, 7.5),
                    .line(12.0, 16.5),
                    .move(8.5, 13.0),
                    .line(12.0, 16.5),
                    .line(15.5, 13.0),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 104),
                Ink(scale: 1.5, cell: 42, x: 10, y: 9, w: 22, h: 24, count: 220),
                Ink(scale: 2.0, cell: 56, x: 13, y: 12, w: 30, h: 32, count: 378),
            ]),
        Icon(
            key: "cancel",
            name: "Cancel",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(5.5, 5.5),
                    .line(18.5, 18.5),
                    .move(18.5, 5.5),
                    .line(5.5, 18.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 8, y: 8, w: 12, h: 12, count: 64),
                Ink(scale: 1.5, cell: 42, x: 12, y: 12, w: 18, h: 18, count: 100),
                Ink(scale: 2.0, cell: 56, x: 16, y: 16, w: 24, h: 24, count: 216),
            ]),
        Icon(
            key: "done",
            name: "Done",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(4.5, 12.5),
                    .line(9.5, 17.5),
                    .line(19.5, 6.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 7, y: 9, w: 14, h: 10, count: 28),
                Ink(scale: 1.5, cell: 42, x: 11, y: 13, w: 20, h: 16, count: 63),
                Ink(scale: 2.0, cell: 56, x: 14, y: 17, w: 28, h: 22, count: 113),
            ]),
        Icon(
            key: "font1",
            name: "Font Size",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(8.75, 9.69),
                    .line(8.75, 8.5),
                    .line(15.25, 8.5),
                    .line(15.25, 9.69),
                    .move(12.0, 8.5),
                    .line(12.0, 15.5),
                    .move(10.635, 15.5),
                    .line(13.365, 15.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 10, y: 10, w: 8, h: 8, count: 30),
                Ink(scale: 1.5, cell: 42, x: 16, y: 15, w: 10, h: 12, count: 58),
                Ink(scale: 2.0, cell: 56, x: 21, y: 21, w: 14, h: 14, count: 104),
            ]),
        Icon(
            key: "font2",
            name: "Font Size",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(7.75, 8.87),
                    .line(7.75, 7.25),
                    .line(16.25, 7.25),
                    .line(16.25, 8.87),
                    .move(12.0, 7.25),
                    .line(12.0, 16.75),
                    .move(10.215, 16.75),
                    .line(13.785, 16.75),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 10, y: 9, w: 8, h: 10, count: 38),
                Ink(scale: 1.5, cell: 42, x: 14, y: 14, w: 14, h: 14, count: 68),
                Ink(scale: 2.0, cell: 56, x: 19, y: 19, w: 18, h: 19, count: 138),
            ]),
        Icon(
            key: "font3",
            name: "Font Size",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(6.5, 8.04),
                    .line(6.5, 6.0),
                    .line(17.5, 6.0),
                    .line(17.5, 8.04),
                    .move(12.0, 6.0),
                    .line(12.0, 18.0),
                    .move(9.69, 18.0),
                    .line(14.31, 18.0),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 9, y: 8, w: 10, h: 12, count: 46),
                Ink(scale: 1.5, cell: 42, x: 13, y: 12, w: 16, h: 18, count: 98),
                Ink(scale: 2.0, cell: 56, x: 17, y: 16, w: 22, h: 24, count: 198),
            ]),
        Icon(
            key: "font4",
            name: "Font Size",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(5.25, 7.22),
                    .line(5.25, 4.75),
                    .line(18.75, 4.75),
                    .line(18.75, 7.22),
                    .move(12.0, 4.75),
                    .line(12.0, 19.25),
                    .move(9.165, 19.25),
                    .line(14.835, 19.25),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 8, y: 7, w: 12, h: 14, count: 60),
                Ink(scale: 1.5, cell: 42, x: 11, y: 11, w: 20, h: 20, count: 104),
                Ink(scale: 2.0, cell: 56, x: 15, y: 14, w: 26, h: 28, count: 238),
            ]),
        Icon(
            key: "font5",
            name: "Font Size",
            parts: [
                Part(paint: .stroke, width: 1.75, opacity: 1.0, cmds: [
                    .move(4.0, 6.39),
                    .line(4.0, 3.5),
                    .line(20.0, 3.5),
                    .line(20.0, 6.39),
                    .move(12.0, 3.5),
                    .line(12.0, 20.5),
                    .move(8.64, 20.5),
                    .line(15.36, 20.5),
                ]),
            ],
            ink: [
                Ink(scale: 1.0, cell: 28, x: 6, y: 6, w: 16, h: 16, count: 72),
                Ink(scale: 1.5, cell: 42, x: 10, y: 9, w: 22, h: 24, count: 142),
                Ink(scale: 2.0, cell: 56, x: 13, y: 12, w: 30, h: 32, count: 260),
            ]),
    ]

    static let toolbarIcons: [String] = ["select", "rect", "ellipse", "line", "arrow", "pen", "highlighter", "text", "number", "mosaic", "undo", "redo", "long", "cancel", "done"]
    static let fontIcons: [String] = ["font1", "font2", "font3", "font4", "font5"]

    /// The icon called `key`, if there is one.
    static func icon(_ key: String) -> Icon? {
        icons.first { $0.key == key }
    }
}

// swiftlint:enable all
