// @generated by windows/tools/the-ffi-structs-match-the-header.py -- do not edit.
// Regenerate with `python3 windows/tools/the-ffi-structs-match-the-header.py --write`,
// then `cargo check --target x86_64-pc-windows-gnu` says which Rust field is wrong.
// Every number is clang's layout of include/ghostty.h for x86_64-windows-gnu.
// Included by ffi.rs so that private structs and fields are in scope.
// One `const` per assert: const evaluation stops at the first panic in a
// block, and a gate that names one mismatch per build hides the others.

// LayoutOut <- ghostty_action_poltergeist_layout_out_s
const _: () = assert!(std::mem::size_of::<LayoutOut>() == 32, "size of LayoutOut != sizeof(ghostty_action_poltergeist_layout_out_s)");
const _: () = assert!(std::mem::align_of::<LayoutOut>() == 8, "align of LayoutOut != alignof(ghostty_action_poltergeist_layout_out_s)");
const _: () = assert!(std::mem::offset_of!(LayoutOut, result) == 0, "LayoutOut.result is not at ghostty_action_poltergeist_layout_out_s.result");
const _: () = assert!(std::mem::offset_of!(LayoutOut, buf) == 8, "LayoutOut.buf is not at ghostty_action_poltergeist_layout_out_s.buf");
const _: () = assert!(std::mem::offset_of!(LayoutOut, cap) == 16, "LayoutOut.cap is not at ghostty_action_poltergeist_layout_out_s.cap");
const _: () = assert!(std::mem::offset_of!(LayoutOut, len) == 24, "LayoutOut.len is not at ghostty_action_poltergeist_layout_out_s.len");

// PoltergeistMark <- ghostty_action_poltergeist_mark_s
const _: () = assert!(std::mem::size_of::<PoltergeistMark>() == 24, "size of PoltergeistMark != sizeof(ghostty_action_poltergeist_mark_s)");
const _: () = assert!(std::mem::align_of::<PoltergeistMark>() == 8, "align of PoltergeistMark != alignof(ghostty_action_poltergeist_mark_s)");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, prefix) == 0, "PoltergeistMark.prefix is not at ghostty_action_poltergeist_mark_s.prefix");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, role) == 8, "PoltergeistMark.role is not at ghostty_action_poltergeist_mark_s.role");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, shielded) == 12, "PoltergeistMark.shielded is not at ghostty_action_poltergeist_mark_s.shielded");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, held) == 13, "PoltergeistMark.held is not at ghostty_action_poltergeist_mark_s.held");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, may_authorise) == 14, "PoltergeistMark.may_authorise is not at ghostty_action_poltergeist_mark_s.may_authorise");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, worker_mentions) == 15, "PoltergeistMark.worker_mentions is not at ghostty_action_poltergeist_mark_s.worker_mentions");
const _: () = assert!(std::mem::offset_of!(PoltergeistMark, persona) == 16, "PoltergeistMark.persona is not at ghostty_action_poltergeist_mark_s.persona");

// PersonaMark <- ghostty_poltergeist_persona_s
const _: () = assert!(std::mem::size_of::<PersonaMark>() == 24, "size of PersonaMark != sizeof(ghostty_poltergeist_persona_s)");
const _: () = assert!(std::mem::align_of::<PersonaMark>() == 8, "align of PersonaMark != alignof(ghostty_poltergeist_persona_s)");
const _: () = assert!(std::mem::offset_of!(PersonaMark, key) == 0, "PersonaMark.key is not at ghostty_poltergeist_persona_s.key");
const _: () = assert!(std::mem::offset_of!(PersonaMark, name) == 8, "PersonaMark.name is not at ghostty_poltergeist_persona_s.name");
const _: () = assert!(std::mem::offset_of!(PersonaMark, deviated) == 16, "PersonaMark.deviated is not at ghostty_poltergeist_persona_s.deviated");
const _: () = assert!(std::mem::offset_of!(PersonaMark, agent_present) == 17, "PersonaMark.agent_present is not at ghostty_poltergeist_persona_s.agent_present");
const _: () = assert!(std::mem::offset_of!(PersonaMark, host_class) == 20, "PersonaMark.host_class is not at ghostty_poltergeist_persona_s.host_class");

// PersonaRow <- ghostty_persona_s
const _: () = assert!(std::mem::size_of::<PersonaRow>() == 16, "size of PersonaRow != sizeof(ghostty_persona_s)");
const _: () = assert!(std::mem::align_of::<PersonaRow>() == 8, "align of PersonaRow != alignof(ghostty_persona_s)");
const _: () = assert!(std::mem::offset_of!(PersonaRow, key) == 0, "PersonaRow.key is not at ghostty_persona_s.key");
const _: () = assert!(std::mem::offset_of!(PersonaRow, name) == 8, "PersonaRow.name is not at ghostty_persona_s.name");

// ClipboardContent <- ghostty_clipboard_content_s
const _: () = assert!(std::mem::size_of::<ClipboardContent>() == 24, "size of ClipboardContent != sizeof(ghostty_clipboard_content_s)");
const _: () = assert!(std::mem::align_of::<ClipboardContent>() == 8, "align of ClipboardContent != alignof(ghostty_clipboard_content_s)");
const _: () = assert!(std::mem::offset_of!(ClipboardContent, mime) == 0, "ClipboardContent.mime is not at ghostty_clipboard_content_s.mime");
const _: () = assert!(std::mem::offset_of!(ClipboardContent, data) == 8, "ClipboardContent.data is not at ghostty_clipboard_content_s.data");
const _: () = assert!(std::mem::offset_of!(ClipboardContent, len) == 16, "ClipboardContent.len is not at ghostty_clipboard_content_s.len");

// ClipboardComplete <- ghostty_clipboard_complete_s
const _: () = assert!(std::mem::size_of::<ClipboardComplete>() == 40, "size of ClipboardComplete != sizeof(ghostty_clipboard_complete_s)");
const _: () = assert!(std::mem::align_of::<ClipboardComplete>() == 8, "align of ClipboardComplete != alignof(ghostty_clipboard_complete_s)");
const _: () = assert!(std::mem::offset_of!(ClipboardComplete, contents) == 0, "ClipboardComplete.contents is not at ghostty_clipboard_complete_s.contents");
const _: () = assert!(std::mem::offset_of!(ClipboardComplete, contents_len) == 8, "ClipboardComplete.contents_len is not at ghostty_clipboard_complete_s.contents_len");
const _: () = assert!(std::mem::offset_of!(ClipboardComplete, available) == 16, "ClipboardComplete.available is not at ghostty_clipboard_complete_s.available");
const _: () = assert!(std::mem::offset_of!(ClipboardComplete, available_len) == 24, "ClipboardComplete.available_len is not at ghostty_clipboard_complete_s.available_len");
const _: () = assert!(std::mem::offset_of!(ClipboardComplete, confirmed) == 32, "ClipboardComplete.confirmed is not at ghostty_clipboard_complete_s.confirmed");
const _: () = assert!(std::mem::offset_of!(ClipboardComplete, remember) == 33, "ClipboardComplete.remember is not at ghostty_clipboard_complete_s.remember");

// ClipboardConfirm <- ghostty_clipboard_confirm_s
const _: () = assert!(std::mem::size_of::<ClipboardConfirm>() == 48, "size of ClipboardConfirm != sizeof(ghostty_clipboard_confirm_s)");
const _: () = assert!(std::mem::align_of::<ClipboardConfirm>() == 8, "align of ClipboardConfirm != alignof(ghostty_clipboard_confirm_s)");
const _: () = assert!(std::mem::offset_of!(ClipboardConfirm, contents) == 0, "ClipboardConfirm.contents is not at ghostty_clipboard_confirm_s.contents");
const _: () = assert!(std::mem::offset_of!(ClipboardConfirm, contents_len) == 8, "ClipboardConfirm.contents_len is not at ghostty_clipboard_confirm_s.contents_len");
const _: () = assert!(std::mem::offset_of!(ClipboardConfirm, available) == 16, "ClipboardConfirm.available is not at ghostty_clipboard_confirm_s.available");
const _: () = assert!(std::mem::offset_of!(ClipboardConfirm, available_len) == 24, "ClipboardConfirm.available_len is not at ghostty_clipboard_confirm_s.available_len");
const _: () = assert!(std::mem::offset_of!(ClipboardConfirm, name) == 32, "ClipboardConfirm.name is not at ghostty_clipboard_confirm_s.name");
const _: () = assert!(std::mem::offset_of!(ClipboardConfirm, can_remember) == 40, "ClipboardConfirm.can_remember is not at ghostty_clipboard_confirm_s.can_remember");

// Target <- ghostty_target_s
const _: () = assert!(std::mem::size_of::<Target>() == 16, "size of Target != sizeof(ghostty_target_s)");
const _: () = assert!(std::mem::align_of::<Target>() == 8, "align of Target != alignof(ghostty_target_s)");
const _: () = assert!(std::mem::offset_of!(Target, tag) == 0, "Target.tag is not at ghostty_target_s.tag");
const _: () = assert!(std::mem::offset_of!(Target, surface) == 8, "Target.surface is not at ghostty_target_s.target");

// Action <- ghostty_action_s
const _: () = assert!(std::mem::size_of::<Action>() == 32, "size of Action != sizeof(ghostty_action_s)");
const _: () = assert!(std::mem::align_of::<Action>() == 8, "align of Action != alignof(ghostty_action_s)");
const _: () = assert!(std::mem::offset_of!(Action, tag) == 0, "Action.tag is not at ghostty_action_s.tag");
const _: () = assert!(std::mem::offset_of!(Action, payload) == 8, "Action.payload is not at ghostty_action_s.action");

// KeyEvent <- ghostty_input_key_s
const _: () = assert!(std::mem::size_of::<KeyEvent>() == 32, "size of KeyEvent != sizeof(ghostty_input_key_s)");
const _: () = assert!(std::mem::align_of::<KeyEvent>() == 8, "align of KeyEvent != alignof(ghostty_input_key_s)");
const _: () = assert!(std::mem::offset_of!(KeyEvent, action) == 0, "KeyEvent.action is not at ghostty_input_key_s.action");
const _: () = assert!(std::mem::offset_of!(KeyEvent, mods) == 4, "KeyEvent.mods is not at ghostty_input_key_s.mods");
const _: () = assert!(std::mem::offset_of!(KeyEvent, consumed_mods) == 8, "KeyEvent.consumed_mods is not at ghostty_input_key_s.consumed_mods");
const _: () = assert!(std::mem::offset_of!(KeyEvent, keycode) == 12, "KeyEvent.keycode is not at ghostty_input_key_s.keycode");
const _: () = assert!(std::mem::offset_of!(KeyEvent, text) == 16, "KeyEvent.text is not at ghostty_input_key_s.text");
const _: () = assert!(std::mem::offset_of!(KeyEvent, unshifted_codepoint) == 24, "KeyEvent.unshifted_codepoint is not at ghostty_input_key_s.unshifted_codepoint");
const _: () = assert!(std::mem::offset_of!(KeyEvent, composing) == 28, "KeyEvent.composing is not at ghostty_input_key_s.composing");

// RuntimeConfig <- ghostty_runtime_config_s
const _: () = assert!(std::mem::size_of::<RuntimeConfig>() == 64, "size of RuntimeConfig != sizeof(ghostty_runtime_config_s)");
const _: () = assert!(std::mem::align_of::<RuntimeConfig>() == 8, "align of RuntimeConfig != alignof(ghostty_runtime_config_s)");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, userdata) == 0, "RuntimeConfig.userdata is not at ghostty_runtime_config_s.userdata");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, supports_selection_clipboard) == 8, "RuntimeConfig.supports_selection_clipboard is not at ghostty_runtime_config_s.supports_selection_clipboard");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, wakeup_cb) == 16, "RuntimeConfig.wakeup_cb is not at ghostty_runtime_config_s.wakeup_cb");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, action_cb) == 24, "RuntimeConfig.action_cb is not at ghostty_runtime_config_s.action_cb");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, read_clipboard_cb) == 32, "RuntimeConfig.read_clipboard_cb is not at ghostty_runtime_config_s.read_clipboard_cb");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, confirm_read_clipboard_cb) == 40, "RuntimeConfig.confirm_read_clipboard_cb is not at ghostty_runtime_config_s.confirm_read_clipboard_cb");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, write_clipboard_cb) == 48, "RuntimeConfig.write_clipboard_cb is not at ghostty_runtime_config_s.write_clipboard_cb");
const _: () = assert!(std::mem::offset_of!(RuntimeConfig, close_surface_cb) == 56, "RuntimeConfig.close_surface_cb is not at ghostty_runtime_config_s.close_surface_cb");

// SurfaceConfig <- ghostty_surface_config_s
const _: () = assert!(std::mem::size_of::<SurfaceConfig>() == 120, "size of SurfaceConfig != sizeof(ghostty_surface_config_s)");
const _: () = assert!(std::mem::align_of::<SurfaceConfig>() == 8, "align of SurfaceConfig != alignof(ghostty_surface_config_s)");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, platform_tag) == 0, "SurfaceConfig.platform_tag is not at ghostty_surface_config_s.platform_tag");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, platform_hwnd) == 8, "SurfaceConfig.platform_hwnd is not at ghostty_surface_config_s.platform");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, userdata) == 16, "SurfaceConfig.userdata is not at ghostty_surface_config_s.userdata");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, scale_factor) == 24, "SurfaceConfig.scale_factor is not at ghostty_surface_config_s.scale_factor");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, font_size) == 32, "SurfaceConfig.font_size is not at ghostty_surface_config_s.font_size");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, working_directory) == 40, "SurfaceConfig.working_directory is not at ghostty_surface_config_s.working_directory");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, command) == 48, "SurfaceConfig.command is not at ghostty_surface_config_s.command");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, env_vars) == 56, "SurfaceConfig.env_vars is not at ghostty_surface_config_s.env_vars");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, env_var_count) == 64, "SurfaceConfig.env_var_count is not at ghostty_surface_config_s.env_var_count");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, initial_input) == 72, "SurfaceConfig.initial_input is not at ghostty_surface_config_s.initial_input");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, wait_after_command) == 80, "SurfaceConfig.wait_after_command is not at ghostty_surface_config_s.wait_after_command");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, context) == 84, "SurfaceConfig.context is not at ghostty_surface_config_s.context");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, poltergeist_chat) == 88, "SurfaceConfig.poltergeist_chat is not at ghostty_surface_config_s.poltergeist_chat");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, history_restore) == 96, "SurfaceConfig.history_restore is not at ghostty_surface_config_s.history_restore");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, scrollback_restore) == 104, "SurfaceConfig.scrollback_restore is not at ghostty_surface_config_s.scrollback_restore");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, width) == 112, "SurfaceConfig.width is not at ghostty_surface_config_s.width");
const _: () = assert!(std::mem::offset_of!(SurfaceConfig, height) == 116, "SurfaceConfig.height is not at ghostty_surface_config_s.height");

// SetTitlePayload <- ghostty_action_set_title_s
const _: () = assert!(std::mem::size_of::<SetTitlePayload>() == 16, "size of SetTitlePayload != sizeof(ghostty_action_set_title_s)");
const _: () = assert!(std::mem::align_of::<SetTitlePayload>() == 8, "align of SetTitlePayload != alignof(ghostty_action_set_title_s)");
const _: () = assert!(std::mem::offset_of!(SetTitlePayload, title) == 0, "SetTitlePayload.title is not at ghostty_action_set_title_s.title");
const _: () = assert!(std::mem::offset_of!(SetTitlePayload, is_explicit) == 8, "SetTitlePayload.is_explicit is not at ghostty_action_set_title_s.is_explicit");

// GString <- ghostty_string_s
const _: () = assert!(std::mem::size_of::<GString>() == 24, "size of GString != sizeof(ghostty_string_s)");
const _: () = assert!(std::mem::align_of::<GString>() == 8, "align of GString != alignof(ghostty_string_s)");
const _: () = assert!(std::mem::offset_of!(GString, ptr) == 0, "GString.ptr is not at ghostty_string_s.ptr");
const _: () = assert!(std::mem::offset_of!(GString, len) == 8, "GString.len is not at ghostty_string_s.len");
const _: () = assert!(std::mem::offset_of!(GString, sentinel) == 16, "GString.sentinel is not at ghostty_string_s.sentinel");

// Info <- ghostty_info_s
const _: () = assert!(std::mem::size_of::<Info>() == 24, "size of Info != sizeof(ghostty_info_s)");
const _: () = assert!(std::mem::align_of::<Info>() == 8, "align of Info != alignof(ghostty_info_s)");
const _: () = assert!(std::mem::offset_of!(Info, build_mode) == 0, "Info.build_mode is not at ghostty_info_s.build_mode");
const _: () = assert!(std::mem::offset_of!(Info, version) == 8, "Info.version is not at ghostty_info_s.version");
const _: () = assert!(std::mem::offset_of!(Info, version_len) == 16, "Info.version_len is not at ghostty_info_s.version_len");

// Diagnostic <- ghostty_diagnostic_s
const _: () = assert!(std::mem::size_of::<Diagnostic>() == 8, "size of Diagnostic != sizeof(ghostty_diagnostic_s)");
const _: () = assert!(std::mem::align_of::<Diagnostic>() == 8, "align of Diagnostic != alignof(ghostty_diagnostic_s)");
const _: () = assert!(std::mem::offset_of!(Diagnostic, message) == 0, "Diagnostic.message is not at ghostty_diagnostic_s.message");

// Keybind <- ghostty_keybind_s
const _: () = assert!(std::mem::size_of::<Keybind>() == 40, "size of Keybind != sizeof(ghostty_keybind_s)");
const _: () = assert!(std::mem::align_of::<Keybind>() == 8, "align of Keybind != alignof(ghostty_keybind_s)");
const _: () = assert!(std::mem::offset_of!(Keybind, action) == 0, "Keybind.action is not at ghostty_keybind_s.action");
const _: () = assert!(std::mem::offset_of!(Keybind, action_len) == 8, "Keybind.action_len is not at ghostty_keybind_s.action_len");
const _: () = assert!(std::mem::offset_of!(Keybind, bound) == 16, "Keybind.bound is not at ghostty_keybind_s.bound");
const _: () = assert!(std::mem::offset_of!(Keybind, trigger) == 20, "Keybind.trigger is not at ghostty_keybind_s.trigger");
const _: () = assert!(std::mem::offset_of!(Keybind, flags) == 32, "Keybind.flags is not at ghostty_keybind_s.flags");
const _: () = assert!(std::mem::offset_of!(Keybind, sequence) == 33, "Keybind.sequence is not at ghostty_keybind_s.sequence");

// Point <- ghostty_point_s
const _: () = assert!(std::mem::size_of::<Point>() == 16, "size of Point != sizeof(ghostty_point_s)");
const _: () = assert!(std::mem::align_of::<Point>() == 4, "align of Point != alignof(ghostty_point_s)");
const _: () = assert!(std::mem::offset_of!(Point, tag) == 0, "Point.tag is not at ghostty_point_s.tag");
const _: () = assert!(std::mem::offset_of!(Point, coord) == 4, "Point.coord is not at ghostty_point_s.coord");
const _: () = assert!(std::mem::offset_of!(Point, x) == 8, "Point.x is not at ghostty_point_s.x");
const _: () = assert!(std::mem::offset_of!(Point, y) == 12, "Point.y is not at ghostty_point_s.y");

// Selection <- ghostty_selection_s
const _: () = assert!(std::mem::size_of::<Selection>() == 36, "size of Selection != sizeof(ghostty_selection_s)");
const _: () = assert!(std::mem::align_of::<Selection>() == 4, "align of Selection != alignof(ghostty_selection_s)");
const _: () = assert!(std::mem::offset_of!(Selection, tl) == 0, "Selection.tl is not at ghostty_selection_s.top_left");
const _: () = assert!(std::mem::offset_of!(Selection, br) == 16, "Selection.br is not at ghostty_selection_s.bottom_right");
const _: () = assert!(std::mem::offset_of!(Selection, rectangle) == 32, "Selection.rectangle is not at ghostty_selection_s.rectangle");

// Text <- ghostty_text_s
const _: () = assert!(std::mem::size_of::<Text>() == 40, "size of Text != sizeof(ghostty_text_s)");
const _: () = assert!(std::mem::align_of::<Text>() == 8, "align of Text != alignof(ghostty_text_s)");
const _: () = assert!(std::mem::offset_of!(Text, tl_px_x) == 0, "Text.tl_px_x is not at ghostty_text_s.tl_px_x");
const _: () = assert!(std::mem::offset_of!(Text, tl_px_y) == 8, "Text.tl_px_y is not at ghostty_text_s.tl_px_y");
const _: () = assert!(std::mem::offset_of!(Text, offset_start) == 16, "Text.offset_start is not at ghostty_text_s.offset_start");
const _: () = assert!(std::mem::offset_of!(Text, offset_len) == 20, "Text.offset_len is not at ghostty_text_s.offset_len");
const _: () = assert!(std::mem::offset_of!(Text, text) == 24, "Text.text is not at ghostty_text_s.text");
const _: () = assert!(std::mem::offset_of!(Text, text_len) == 32, "Text.text_len is not at ghostty_text_s.text_len");

// crate::keys::TriggerC <- ghostty_input_trigger_s
const _: () = assert!(std::mem::size_of::<crate::keys::TriggerC>() == 12, "size of crate::keys::TriggerC != sizeof(ghostty_input_trigger_s)");
const _: () = assert!(std::mem::align_of::<crate::keys::TriggerC>() == 4, "align of crate::keys::TriggerC != alignof(ghostty_input_trigger_s)");
const _: () = assert!(std::mem::offset_of!(crate::keys::TriggerC, tag) == 0, "crate::keys::TriggerC.tag is not at ghostty_input_trigger_s.tag");
const _: () = assert!(std::mem::offset_of!(crate::keys::TriggerC, key) == 4, "crate::keys::TriggerC.key is not at ghostty_input_trigger_s.key");
const _: () = assert!(std::mem::offset_of!(crate::keys::TriggerC, mods) == 8, "crate::keys::TriggerC.mods is not at ghostty_input_trigger_s.mods");
